r"""LaTeX for the camera-ready manuscript, from results/summary/ (step 5).

Reads results/summary/ (written by summarize_results.py) and writes latex/:

  numbers.tex                    every entry of numbers.json as \res{<key>}
  tables/bias_by_rho_compact.tex main text: mean bias correction per ρ regime
  tables/bias_by_rho.tex         appendix: value, correction, seed-std and gap to H(Y)
  tables/heldout_vs_insample.tex appendix: held-out vs in-sample, deepest layer
  tables/baseline_sensitivity.tex appendix: Pearson r for every baseline setting
  tables/occupancy.tex           appendix: ρ and singleton fractions, Composite and WBC
  tables/occupancy_mnist.tex     appendix: ρ per MNIST architecture and PCA dimension
  tables/label_permutation.tex   appendix: clean vs label-permuted networks
  tables/ordering.tex            appendix: quotient spread over visiting orders, per ε

Copy latex/ into the manuscript next to figures/. The paper loads numbers.tex
in its preamble and writes a number as \res{fig2.r.binning8}; an unknown key
prints **??key** and a LaTeX warning. Tables are bare tabular environments
(booktabs) to \input inside the paper's own table float and caption.

Formatting: integers as they are, floats with three decimals. Keys that hold
a fraction (accuracy, *_frac, relative spread) also get a percent version
under <key>.pct, with one decimal and no % sign.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
SUMMARY = REPO / "results" / "summary"
OUT = REPO / "latex"

ESTIMATOR_NAMES = {
    "plug_in": "Plug-in",
    "miller_madow": "Miller--Madow",
    "grassberger": "Grassberger",
    "chao_shen": "Chao--Shen",
    "chao_wang_jost": "Chao--Wang--Jost",
    "ansb": "ANSB$^\\dagger$",
}
RHO_RANGES = {"rho<0.05": "$\\rho < 0.05$", "rho>0.3": "$\\rho > 0.3$", "rho>0.9": "$\\rho > 0.9$"}
DATASET_NAMES = {"composite": "Composite", "wbc": "WBC", "mnist": "MNIST"}
PERCENT_HINTS = ("accuracy", "_frac", "relative_spread")


def f3(x) -> str:
    """Three decimals; minus as in math mode. Missing values as an en dash."""
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "--"
    return f"{x:.3f}".replace("-", "$-$")


def by_arch(df: pd.DataFrame) -> pd.DataFrame:
    """Rows ordered by width, then depth."""
    key = df["arch_str"].map(lambda a: (int(a.strip("[]").split(",")[0]), a.count(",")))
    return df.assign(_k=key).sort_values("_k", kind="stable").drop(columns="_k")


def arch(arch_str: str) -> str:
    return arch_str.replace(" ", "")


def write(name: str, text: str) -> None:
    path = OUT / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {name}")


def tabular(colspec: str, header: list[str], rows: list[list[str]], groups: list[int] = ()) -> str:
    """A booktabs tabular; `groups` are row indices that get a \\midrule above them."""
    lines = [f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", " & ".join(header) + " \\\\", "\\midrule"]
    for i, row in enumerate(rows):
        if i in groups:
            lines.append("\\midrule")
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "% Generated by scripts/write_latex.py from results/summary/; do not edit.\n" + "\n".join(lines)


# ---------------------------------------------------------------------------
# numbers.tex
# ---------------------------------------------------------------------------
def tex_value(value) -> str:
    if isinstance(value, bool) or isinstance(value, str):
        return str(value).replace("_", "\\_")
    if isinstance(value, int) or (isinstance(value, float) and value.is_integer() and abs(value) >= 1):
        return f"{int(value):,}".replace(",", "{,}")
    return f3(value).replace("$-$", "-")   # \res is used in math mode as well as text


def numbers_tex() -> None:
    numbers = json.loads((SUMMARY / "numbers.json").read_text())
    lines = [
        "% Generated by scripts/write_latex.py from results/summary/numbers.json; do not edit.",
        "% Usage: \\res{<key>}, e.g. $r = \\res{fig2.r.binning8}$; keys are listed in SUMMARY.md.",
        "\\makeatletter",
        "\\newcommand{\\res}[1]{\\ifcsname res@#1\\endcsname\\csname res@#1\\endcsname"
        "\\else\\PackageWarning{numbers}{Unknown result key `#1'}\\textbf{??\\detokenize{#1}}\\fi}",
        "\\newcommand{\\defres}[2]{\\expandafter\\def\\csname res@#1\\endcsname{#2}}",
        "\\makeatother",
    ]
    for key, value in numbers.items():
        lines.append(f"\\defres{{{key}}}{{{tex_value(value)}}}")
        if isinstance(value, float) and any(h in key for h in PERCENT_HINTS):
            lines.append(f"\\defres{{{key}.pct}}{{{100 * value:.1f}}}")
    write("numbers.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------
def bias_by_rho() -> None:
    df = pd.read_csv(SUMMARY / "bias_corrections_by_rho.csv").set_index(["rho_range", "estimator"])
    n = {r: int(df.loc[(r, "plug_in"), "n_cells"]) for r in RHO_RANGES}

    # Main text: mean correction (plug-in − corrected), one column per ρ regime
    header = ["Estimator"] + [f"{lab} ($n={n[r]}$)" for r, lab in RHO_RANGES.items()]
    rows = [[ESTIMATOR_NAMES[e]] + [f3(df.loc[(r, e), "mean_correction"]) for r in RHO_RANGES]
            for e in ESTIMATOR_NAMES if e != "plug_in"]
    write("tables/bias_by_rho_compact.tex", tabular("l" + "r" * len(RHO_RANGES), header, rows))

    # Appendix: every statistic, one block per ρ regime
    header = ["$\\rho$ range", "Estimator", "Value", "Correction", "Seed std", "Gap to $H(Y)$"]
    rows, groups = [], []
    for r, lab in RHO_RANGES.items():
        if rows:
            groups.append(len(rows))
        for e in ESTIMATOR_NAMES:
            s = df.loc[(r, e)]
            rows.append([f"{lab} ($n={n[r]}$)" if e == "plug_in" else "", ESTIMATOR_NAMES[e],
                         f3(s["mean_value"]), f3(s["mean_correction"]),
                         f3(s["mean_seed_std"]), f3(s["mean_gap_to_H_Y"])])
    write("tables/bias_by_rho.tex", tabular("llrrrr", header, rows, groups))


def heldout_vs_insample() -> None:
    df = pd.read_csv(SUMMARY / "heldout_vs_insample.csv")
    df = df[df["layer"] == df["arch_str"].str.count(",") + 1]           # deepest layer
    header = ["Dataset", "Architecture", "$\\rho$ held-out", "$\\rho$ in-sample",
              "$\\hat I$ held-out", "$\\hat I$ in-sample", "$\\Delta \\hat I$"]
    rows, groups = [], []
    for ds, sub in by_arch(df).groupby("dataset", sort=False):
        if rows:
            groups.append(len(rows))
        for i, (_, s) in enumerate(sub.iterrows()):
            rows.append([DATASET_NAMES[ds] if i == 0 else "",
                         f"$[{arch(s.arch_str)[1:-1]}]$", f3(s.rho_heldout), f3(s.rho_insample),
                         f3(s.plug_in_bits_heldout), f3(s.plug_in_bits_insample), f3(s.delta_plug_in)])
    write("tables/heldout_vs_insample.tex", tabular("llrrrrr", header, rows, groups))


def baseline_sensitivity() -> None:
    df = pd.read_csv(SUMMARY / "baseline_sensitivity.csv")
    est = df["estimator"].map(lambda e: "ksg" if e.startswith("ksg") else e)
    wide = df.assign(estimator=est).pivot_table(index=["family", "setting"], columns=["group", "estimator"],
                                                values="pearson_r", sort=False)
    submitted = set(df.loc[df["submitted"], "setting"])
    header = ["Baseline", "Setting",
              "\\multicolumn{2}{c}{Composite + WBC ($n=60$)}", "\\multicolumn{2}{c}{MNIST FC ($n=15$)}"]
    sub = ["", "", "plug-in", "MM", "plug-in", "MM"]
    rows, groups, last = [], [], None
    for (family, setting), s in wide.iterrows():
        if family != last and last is not None:
            groups.append(len(rows))
        label = setting.removeprefix(family) + ("$^*$" if setting in submitted else "")
        if family == "ksg":
            vals = [f3(s[("composite+wbc", "ksg")]), "", f3(s[("mnist", "ksg")]), ""]
        else:
            vals = [f3(s[(g, e)]) for g in ("composite+wbc", "mnist") for e in ("plug_in", "miller_madow")]
        rows.append([{"binning": "Binning ($K$)", "kmeans": "$k$-means ($K$)", "ksg": "KSG ($k$)"}[family]
                     if family != last else "", label] + vals)
        last = family
    text = tabular("llrrrr", header, rows, groups)
    first = " & ".join(header) + " \\\\\n"
    text = text.replace(first + "\\midrule", first + "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
                        + " & ".join(sub) + " \\\\\n\\midrule")
    write("tables/baseline_sensitivity.tex", text)


def occupancy() -> None:
    df = pd.read_csv(SUMMARY / "occupancy.csv")
    df = df[df["protocol"] == "heldout"]
    cw = df[df["dataset"] != "mnist"]
    header = ["Dataset", "Architecture", "Regions", "$\\rho$", "Singleton regions", "Singleton samples"]
    rows, groups = [], []
    for ds, sub in by_arch(cw).groupby("dataset", sort=False):
        if rows:
            groups.append(len(rows))
        for i, (_, s) in enumerate(sub.iterrows()):
            rows.append([DATASET_NAMES[ds] if i == 0 else "",
                         f"$[{arch(s.arch_str)[1:-1]}]$", f"{s.num_regions:.1f}", f3(s.rho),
                         f3(s.singleton_region_frac), f3(s.singleton_sample_frac)])
    write("tables/occupancy.tex", tabular("llrrrr", header, rows, groups))

    mn = df[df["dataset"] == "mnist"].pivot_table(index="arch_str", columns="target_dim", values="rho", sort=False)
    mn = mn.loc[sorted(mn.index, key=lambda a: int(a.strip("[]").split(",")[0]))]
    header = ["Architecture"] + [f"$d = {d}$" for d in mn.columns]
    rows = [[f"$[{arch(a)[1:-1]}]$"] + [f3(v) for v in s] for a, s in mn.iterrows()]
    write("tables/occupancy_mnist.tex", tabular("l" + "r" * len(mn.columns), header, rows))


def label_permutation() -> None:
    df = pd.read_csv(SUMMARY / "label_permutation.csv")
    test = df[(df["protocol"] == "heldout") & (df["labels"] == "true_labels")]
    fit = df[(df["protocol"] == "train") & (df["labels"] == "train_labels")].set_index(["dataset", "arch_str"])
    header = ["Dataset", "Architecture", "Labels", "Test acc.", "Train-label acc.", "$\\rho$",
              "$\\hat I$", "$\\hat I_{\\mathrm{func}}$", "$\\rho_{\\mathrm{func}}$"]
    rows, groups = [], []
    for ds, sub in test.groupby("dataset", sort=False):
        if rows:
            groups.append(len(rows))
        sub = by_arch(sub.sort_values("condition"))
        for i, (_, s) in enumerate(sub.iterrows()):
            train_acc = fit.loc[(ds, s.arch_str), "accuracy"] if s.condition == "permuted" else None
            rows.append([DATASET_NAMES[ds] if i == 0 else "",
                         f"$[{arch(s.arch_str)[1:-1]}]$", s.condition,
                         f"{100 * s.accuracy:.1f}\\%",
                         "--" if train_acc is None else f"{100 * train_acc:.1f}\\%",
                         f3(s.rho), f3(s.plug_in_bits), f3(s.plug_in_func_bits), f3(s.rho_func)])
    write("tables/label_permutation.tex", tabular("lllrrrrrr", header, rows, groups))


def ordering() -> None:
    df = pd.read_csv(SUMMARY / "ordering_by_epsilon.csv")
    header = ["Layers", "$\\varepsilon$", "Cells", "Median", "95th pct.", "Max", "Max / $R$",
              "Max $\\Delta \\hat I^{\\mathrm{MM}}_{\\mathrm{func}}$"]
    rows, groups = [], []
    for scope, sub in df.groupby("scope", sort=False):
        if rows:
            groups.append(len(rows))
        for i, (_, s) in enumerate(sub.iterrows()):
            rows.append([scope if i == 0 else "", f"{s.epsilon:g}", str(int(s.n_cells)),
                         f"{s.spread_median:g}", f"{s.spread_p95:.1f}", str(int(s.spread_max)),
                         f"{100 * s.relative_spread_max:.1f}\\%", f3(s.miller_madow_func_spread_max)])
    write("tables/ordering.tex", tabular("lrrrrrrr", header, rows, groups))


def main() -> None:
    print("Writing latex/:")
    numbers_tex()
    bias_by_rho()
    heldout_vs_insample()
    baseline_sensitivity()
    occupancy()
    label_permutation()
    ordering()


if __name__ == "__main__":
    main()
